### ISSUE TITLE
Introduce 'illustrator' field for a post

### ISSUE THREAD

**Issue by briggySmalls** [jerome-toole/skindeep#1]
Each post should have an Illustrator field, just as each post has an author.
It is expected that this will be displayed underneath the author when displaying a single post.

**Comment by briggySmalls** [comment]
The solution proposed will use the Advanced Custom Fields (ACF) plugin to introduce the Illustrator custom field into the *Edit Post* admin form.
Given this is the case, it might make sense to also incorporate the custom author field into ACF too - currently managed by the Custom Author Byline (CAB) plugin.
CAB saves the custom author field for a given post into the *wp_metapost* table, with `wp_metakey='author'`. An ACF field with name 'author' is expects a *wp_metapost* row of the same form, making the two plugins a straight swap (no database manipulation required).

**Comment by jerome-toole** [comment]
Where you at on this?

**Comment by briggySmalls** [comment]
All the server-side code is implemented.
I am waiting on hearing from Sylvia/Arieh on how they want Author/Illustrator rendered on a post. Apparently they don't want the black box (where author is currently located) to get any larger.
It sounds like they want somethings like:
> Author: XXXX
> Illustrator: YYYY

Underneath the black box and above the text of the post.

**Comment by briggySmalls** [comment]
Branch iss1 created to resolve this issue.
Failed to link commit https://github.com/jerome-toole/skindeep/commit/bc2cde2091abae4837ef34ae7115da5c4a151050 to here, so doing it manually now!

**Comment by jerome-toole** [comment]
yeah, the black box is not really looking good at all I don't think. Covers up too much of the image.

Maybe it should change to be more like this: http://codepen.io/jerome-toole/pen/pNPzxy where the background is just behind the text rather than becoming a block when it wraps to the next line.
