### ISSUE TITLE
Redundant Imagining 2043 pages

### ISSUE THREAD

**Issue by briggySmalls** [jerome-toole/skindeep#12]
At the moment there are two pages discussing the Imagining 2043 issue:
- http://www.skindeepmag.com/category/imagining2043/
- http://www.skindeepmag.com/product/issue-5-imagining-2043/

The first discusses where the issue is sold, and has an out-of-date discussion of what 'will' be in the edition.
The second is the conventional product page, where someone can purchase a print copy.

The content here could be collapsed into a single page. However it should still be quick to access the page.

It is proposed that the list of vendors is added to the product page. The 'category' page is deleted, and its position on the menu is replaced with the product page.

**Comment by jerome-toole** [comment]
is this done?

**Comment by briggySmalls** [comment]
Sorry, this was live but I forgot to commit.
Had to hide Jetpack's 'Related Posts' on product pages before I could put the bookshop content into the product description.

**Comment by briggySmalls** [comment]
Perhaps a separate issue, but WooCommerce's product description box has a tab labelled 'Description' then immediately before any content it prefixes 'Product Description'.
This is pretty distracting.
The .php file responsible for prefixing 'Product Description' to the content contains the following statement in the header:

> This template can be overridden by copying it to yourtheme/woocommerce/single-product/tabs/description.php

So perhaps that could be done.

**Comment by briggySmalls** [comment]
Furthermore I have kept the list of vendors as centre-aligned - how it was on the category page.
However IMO this looks kinda pants on mobile. Do you have a suggestion on how to format this? OR perhaps we can leave that with Skin Deep editors as it can be modified within the GUI

**Comment by briggySmalls** [comment]
Finally, should I delete the Category page now? What is the policy on deleting pages? I notice that there are quite a few unused pages scattered around...

**Comment by jerome-toole** [comment]
Yes, go ahead and delete. I think they all go in the 'Trash' anyway and can be retrieved. 

The vendors list is left-aligned by default. It's the WYSIWYG editor that has made it central. That whole section doesn't look great though. I'm looking forward to the day when there's some budget to redo the whole thing 😂

**Comment by jerome-toole** [comment]
Oh, and on the 'description' thing, definitely copy over and remove that annoying text. 

It should be as simple as that. You just make a directory called `woocommerce/` and you can copy all the templates you want to into there and Woocommerce will prioritise using 'our' version before the plugins default.

Is this issue close then?

**Comment by briggySmalls** [comment]
Done!

**Comment by jerome-toole** [comment]
😄
