### ISSUE TITLE
Restyle mailing list header button

### ISSUE THREAD

**Issue by briggySmalls** [jerome-toole/skindeep#44]
From @CiaranChris re: 'join our mailing list' button in header:
> Loving the button, perhaps there’s a more visual way if it sits next to the social icons and then those could sit as a complete set rather than text within in a button.
 
Button should be restyled to integrate better with the social icons. Some thought should be given to how that should look.

Perhaps an icon like:
![image](https://cloud.githubusercontent.com/assets/11054133/26607121/e06f1b34-458c-11e7-816d-f2501c4cdf16.png)

**Comment by CiaranChris** [comment]
Agreed, I'll mock one up tonight. It should sit as though its apart of the family of social icons

**Comment by CiaranChris** [comment]
like this, let me know if there are any troubles with it. Do we need to select a colour for it to change to when hovered over?

I tried to match the existing ones. Maybe in the future we could get a custom set done.

![mail-01](https://cloud.githubusercontent.com/assets/29028655/26701700/0ae4e9b4-471a-11e7-8234-4835b27ad604.png)

**Comment by briggySmalls** [comment]
Hey Ciaran.

So it turns out the icons are all part of an open source 'font' set called [genericons](https://github.com/Automattic/Genericons). There are a load of icons, not just social media logos, part of this set and so I have picked the one named 'subscribe' for our purposes.

You can use this [gallery of the available icons](http://expo.se/sverigedemokraterna/old/wp-content/themes/twentyfifteen/genericons/example.html#bold) if you would prefer to use the more simple 'Mail' envelope one, or something like that. Plus if you would really like to use a custom one we could look at adding a new icon to the font.

Cheers,
Sam

**Comment by CiaranChris** [comment]
Seen it. Into it. It works and i think it gets the point across. Maybe we go for the one without the '+' on it just for visual consistency with the other blocks. 

 Could we just check the time that the overlay comes up though. I think its a little slow.

**Comment by briggySmalls** [comment]
Sorry, I forgot to refresh the setting after making a change.

It should be working now (immediately shown)

**Comment by briggySmalls** [comment]
Changed it to the one without the +
