### ISSUE TITLE
Navigation bar type

### ISSUE THREAD

**Issue by CiaranChris** [jerome-toole/skindeep#47]
Could we change the weight of the font to a lighter weight on the navigation bar. 
![navigationbartype](https://cloud.githubusercontent.com/assets/29028655/26701867/910fe142-471a-11e7-9fa0-566f4c61a753.png)

**Comment by briggySmalls** [comment]
Try that on for size! The font weight increments seem pretty large on my screen...you up it by one unit and the gets much much larger. Let me know what you think.

*note: may need to force refresh to make sure CSS is updated on your machine. On mac that is ⌘+⇧+r*

**Comment by CiaranChris** [comment]
Looking good! that you
