### ISSUE TITLE
Grid Headline and date

### ISSUE THREAD

**Issue by CiaranChris** [jerome-toole/skindeep#48]
Could we make the headline medium weight of font please and add date to post?
![gridheadline](https://cloud.githubusercontent.com/assets/29028655/26702417/dd8e5bdc-471c-11e7-939c-0bc0cbcd9d9c.png)

**Comment by briggySmalls** [comment]
Try that on for size! The font weight increments seem pretty large on my screen...you up it by one unit and the gets much much larger. Let me know what you think.

*note: may need to force refresh to make sure CSS is updated on your machine. On mac that is ⌘+⇧+r*

**Comment by CiaranChris** [comment]
Yo yo. the bold is a little to bold, is it possible to take it down from 600 weight to a 450/500?
![screen shot 2017-06-04 at 20 24 20](https://cloud.githubusercontent.com/assets/29028655/26764701/db430dd4-4963-11e7-85d7-e2b3e020772a.png)

**Comment by CiaranChris** [comment]
![gridheadline-new](https://cloud.githubusercontent.com/assets/29028655/26764752/1f2de0ea-4965-11e7-96f2-042716417687.png)
Would it be possible to update 'Date' next to authors name like this so there is a little more space between.

perhaps going forward once the decision has been made on a redesign of the site, they might read the section the piece belongs in rather than the date?
