### ISSUE TITLE
Slider images

### ISSUE THREAD

**Issue by CiaranChris** [jerome-toole/skindeep#52]
Currently we are using dimensions 1200px by 514px, but the slider images are still quite blurry.

**Comment by briggySmalls** [comment]
It turns out we are using a plugin that sets the image sizes smartly. Whilst it was true the theme was trying to serve a lower-res image, the plugin overrode that behaviour, so that was a red herring.

On my computer the images look blurry because:
1. The image has a maximum resolution of 1200px by 512px
2. My retina screen is trying to fill an area of 1440px by 616.797px

So the options are:
- Fix the slider image size to the maximum (1200px), i.e. reducing the screen area of the slider on retina screens.
- Upload higher-resolution images.

Up to you guys. This also applies for the image shown above the header on a single post too.

**Comment by CiaranChris** [comment]
What if we were to up it to 1500px wide, and anything larger (desktops, etc) it's just fixed at that dimension. 

I think a lot of people would be viewing it on a laptop smaller than yours and hopefully mostly on mobile.

**Comment by briggySmalls** [comment]
Yeah that would work. I'll make the change now and then you guys should use 1500px from now 👍

**Comment by CiaranChris** [comment]
Sweet! just to confirm the new size will be 1500px by 640px?

**Comment by briggySmalls** [comment]
Yup.
So images before were set to be stretched to fill 100% of the width of the screen. The height would be whatever corresponded to 100% width (so dependent on the aspect ratio of picture).
I've set the _max-width_ to 1500px. So images will try to fill 100% of the width of the screen, however will not ever be stretched wider than 1500px (i.e. on v wide screens).
So all of your previous images that are size 1200px will still be stretched wider. On my computer that is 1440px. TBH we could make it 1200px max width and then this would work for all pictures from before.
On my screen that would look like:
<img width="1440" alt="screen shot 2017-07-22 at 18 57 25" src="https://user-images.githubusercontent.com/11054133/28493458-a0fe139a-6f0f-11e7-81b1-7507a09ea83c.png">
vs
<img width="1440" alt="screen shot 2017-07-22 at 20 08 22" src="https://user-images.githubusercontent.com/11054133/28494009-85529a1c-6f19-11e7-89da-a536dbe7c95e.png">

**Comment by CiaranChris** [comment]
Hmm, I see. I definitely think the fuller option looks better, but I know the team is really routing for clearer, sharper images for the slider. Is it possible to add the other image on the sliders to either side i.e. 

![screen-shot-2017-07-23-at-21 16 38](https://user-images.githubusercontent.com/29028655/28502580-74ef5dac-6fed-11e7-8ba1-61f13ce6e494.jpg)

only if this can be easily done and doesn't require a lot on your side. However i did just realise that this will force me to come up with a new way to display headline and sell of each piece. Are we able to loose the authors name from the slider or is that part of the theme?

Perhaps for the redesign we jump to 1500px, or we could find a way to incorporate a 3:2 aspect ratio for the slider, maybe 1920 px by 1280px, perhaps this would be a way to cover ourselves for the future.
