### ISSUE TITLE
Article Format

### ISSUE THREAD

**Issue by CiaranChris** [jerome-toole/skindeep#56]
Would it be possible to redesign the article format to appear a little more consistent with the more fixed pages of the site (About, Submissions)

![article-layout](https://user-images.githubusercontent.com/29028655/27002631-52cb5b08-4dde-11e7-8f01-b00a55c67082.png)

Main change is removing the headline from the image

Headline = Roboto condensed, matching the home page.

Also, it appears that the 'written by' and 'photography by' have fallen off. is that a Embedded thing or is it more when the article is created that needs to be typed in?

**Comment by briggySmalls** [comment]
That should do it? 😄

**Comment by briggySmalls** [comment]
While cruising around the site I've really been enjoying the new article heading. Good spot 👍
