### ISSUE TITLE
Banner background colour

### ISSUE THREAD

**Issue by CiaranChris** [jerome-toole/skindeep#58]
Hey,

Is it possible to get the background colour of the gif area changed or if i could do it myself?

and if its possible to do gradients or just 2 colours?

if not its all good. The pink works quite well.

the hex codes: ffedd6 to dcf0f1

**Comment by briggySmalls** [comment]
Hey Ciaran,

Yep this is now configurable through the UI. Unfortunately, however, you can only choose a single colour (not gradient).

If you go to **Appearance > Customize** then select **Color Options > Header Color Options** you can set the **Header Image Background Color** field to the colour you want.

😉
